### ISSUE TITLE
Destructive Bug With Weight Balancing Feature

### ISSUE THREAD

**Issue by dboi88** [UmbraSpaceIndustries/USITools#105]
I've discovered a few bugs in the weight balancing feature that tear the crafts apart.
I tested on a clean install with the newest release of MKS and then updated to the current release of USI tools, no other mods installed.

First example uses a basic set up and the craft is launched with the weight balancing feature turned off.
When you turn on the weight balancing feature everything is fine until you come out of warp and then the craft tears itself apart.
http://i.imgur.com/scVLT54.gifv

The second example uses a basic set up and the craft is launched with the weight balancing feature turned on. When it's turned off the attached parts start to drift away. When you enter warp they come back, when you exit warp they jump right off the craft into the distance.
http://i.imgur.com/ysNK2if.gif

I've attached a save file with the two example crafts in orbit.
[persistent.txt](https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/files/1017133/persistent.txt)

**Comment by dboi88** [comment]
I've done a lot of further testing with some basic part modules to try and find a fix. I've pretty certain this is a stock bug. I've tested setting physics significance at all sorts of different game events and get the same results. The below module is the most basic test and will 100% reliable produce the same results when coming out of warp, or using the orbit editor. Setting it in the cfg works perfectly fine, hence no reports of stock problems.

```
public class Class1 : PartModule
    {
        ///Set part physics significane Full
        public override void OnStart(StartState state)
        {
            part.physicalSignificance = Part.PhysicalSignificance.NONE;
        }
    }
```
If you are able to also confirm this i'll add it the info to the bug tracker.

**Comment by dboi88** [comment]
I've now found a work around that avoids using physicalSignificance alltogether and instead moves the CofM for each child part to match the CofM of the weight distributor.

I can throw together a PR if you are interested?

**Comment by BobPalmer** [comment]
Please :)

**Comment by dboi88** [comment]
PR Submitted
