### ISSUE TITLE
Enhancement Request:  Inflatable Heat Shielding   AKA: Ballute heat shields

### ISSUE THREAD

**Issue by rottielover** [UmbraSpaceIndustries/USITools#13]
Ref Material:  Movie 2010: The year we make contact Lenov model: http://www.truedimensions.com/lego/customs/2010/     /  NASA's hypersonic inflatable heat shield: http://www.gizmag.com/inflatable-heat-shield/23416/

Link to pic of airbag in movie: http://kunochan.com/wp-content/uploads/2010/02/2010_11_630x354.jpg

SFX pic of movie during the AeroBreak, kinda shows the shaping:  http://www.projectrho.com/public_html/rocket/images/landing/2010_aerobrake3Tb.jpg

Another shot from the movie of an internal screen of the ship, showing a diagram of what the shielding looks like:  http://www.projectrho.com/public_html/rocket/images/landing/2010_aerobrake1.jpg

Also see this:  http://www.projectrho.com/public_html/rocket/landing.php

Reference is "Magneto-hydrodynamic heat shield."  (for the basic shape, the concept is a little farther away technically)

Finally the best description:  http://www.daviddarling.info/encyclopedia/B/ballute.html

What I'm requesting is non-Spherical inflatable heat shielding.  Originally I was going to modify the part files for the air-bags to add ablative shielding (let's call it a "coating" lol)  but sphere's hanging off the ship aren't going to correctly shield a ship attempting an aerobrake maneuver.  

I propose an interlocking system, where by a central conical shield (these have been done before) _could_ be at the center with pie wedge rounded shaped bags around it, this would greatly increase the diameter of the shielded area behind.  What's nice about this idea is that the central conical piece becomes optional, meaning that the size 3 or 4 size parts would take a conical shield plus 4 to 6 radial bags.  Smaller size 1 or 2 ships might need only 2 to 4 radial bags, OR a conical in the front.

This would increase player options for builds.

**Comment by BobPalmer** [comment]
Closing as I'm adding a 10m inflatable heat shield to stock ;)

**Comment by rottielover** [comment]
That's just about the best news I've heard in the last two days (yea rough times). 

Thank you and the whole team for your hard work and dedication to KSP.   It's really helped me to keep my sanity lately!

Best Regards,

Scott (aka Rottielover)

**Comment by Jimbodiah** [comment]
There is a mod for those parts called "Inline Ballutes" with some balloon type verions, and Chaka has a few bottom mounted inflatable heat shield in his pack (don't know if they are his). 

Never the less, looking forward to seeing Rover's version!

**Comment by rottielover** [comment]
Back in Oct. 2014 that mod did not exist, looks like it released around a full year after I submitted this request.

**Comment by Jimbodiah** [comment]
Haha :)  :+1:
