### ISSUE TITLE
Electricity handling in USI_Converter

### ISSUE THREAD

**Issue by Ramarren** [UmbraSpaceIndustries/USITools#14]
In USI_Converter.cs line 133:

``` c#
double maxElectricityDesired = Math.Min(desiredAmount, conversionRate*Math.Max(Utilities.ElectricityMaxDeltaTime, TimeWarp.fixedDeltaTime)); // Limit the max electricity consumed when reloading a vessel
```

shouldn't Math.Max be Math.Min as well? Otherwise ElectricityMaxDeltaTime seems misnamed and why would EC consumption be bound from below?

I noticed this because I tried creating a USI_Converter consuming 5000 EC/s and it runs out at higher warps. This fragment would fix that if it actually clamped an update tick for ECs to a second.

**Comment by BobPalmer** [comment]
(Closing as this module is deprecated)
