### ISSUE TITLE
UTech Nuclear Science Ink. resources depreciated

### ISSUE THREAD

**Issue by Era4721** [UmbraSpaceIndustries/USITools#147]
UTech Nuclear Science Ink. by Lgg159 adds in fusion/anti-matter engines and fuel tanks, but right clicking the engines bugs out any right click function for anything else, and the fuel tanks don't give the listed resource (hydrogen)

I'm not sure if that mod is apart of this one or by a seperate person, but there's no way to get into contact with them about it so here I am 

https://spacedock.info/mod/2371/UTech Nuclear Science Ink. this is the link to their page? I'm not sure if they're apart of USI

**Comment by BobPalmer** [comment]
They are not - no idea who that is.
