### ISSUE TITLE
Attribute 'URL' in USI.version doesn't link to the right place

### ISSUE THREAD

**Issue by clement-michelet** [UmbraSpaceIndustries/USITools#15]
Hi,

I'm not familiar with mod update on KSP but the attribute 'URL' in latest (and previous) release of USI Tools doesn't point to the right place.

The current value is `https://raw.githubusercontent.com/BobPalmer/UmbraSpaceIndustries/master/GameData/UmbraSpaceIndustries/USI.version` which lead to a not found request.
The file is accessible through this URL `https://raw.githubusercontent.com/BobPalmer/UmbraSpaceIndustries/master/GameData/000_USITools/USI.version`.

Regards,
Clément

**Comment by BobPalmer** [comment]
Thanks - fixed in next patch
