### ISSUE TITLE
Make sure the USI Converter info text has enough precision to never show 0.00

### ISSUE THREAD

**Issue by haslingerm** [UmbraSpaceIndustries/USITools#2]
When using very small ratios (e.g. 0.000061) for In-/Output resources the info text in the VAB currently shows 0.00 due to rounding.
I suggest that the Utilities method called to format the value assures that the precision is increased until at least one relevant digit is displayed (e.g. 0.00006 in the above example).

**Comment by BobPalmer** [comment]
Module is deprecated
