### ISSUE TITLE
Extended TAC-LS compatibility

### ISSUE THREAD

**Issue by DenisDanilov** [UmbraSpaceIndustries/USITools#28]
I bugged you a while back on the KSP forum as user DDE. And yes, I've tried rewriting the Kontainers to my liking, but I've had minor slip-ups, and I assume someone less amateurish might be able to handle the Firespitter configs with much less pain.

You've once described the process of replacing Firespitter configs as painful. I have to disagree. See, PorkJet's Fuel Switch plug-in contains the following config:

```
@PART[miniFuelTank]
{
!RESOURCE[LiquidFuel] {}
!RESOURCE[Oxidizer] {}
MODULE
{

    name = FSfuelSwitch
    resourceNames = LiquidFuel,Oxidizer;LiquidFuel;Oxidizer
    resourceAmounts = 18,22;36;44
    basePartMass =0.025
    //tankMass = 0;0;0
    //tankCost =0;0;0
    displayCurrentTankCost = false
    hasGUI = true
    availableInFlight = false
    availableInEditor = true
    showInfo = true
    }

}
```

However, Ven's Stock Overhaul adds Oscar-D and Oscar-E tanks, which were getting the same module (and hence same capacities). So I had to write my first KSP "mod":

```
@PART[OscarEtank]:FINAL
{
 !MODULE[FSfuelSwitch] {}
}
@PART[OscarDtank]:FINAL
{
 !MODULE[FSfuelSwitch] {}
}
@PART[OscarDtank]:FINAL
{
 MODULE
 {
  name = FSfuelSwitch
  resourceNames = LiquidFuel,Oxidizer;LiquidFuel;Oxidizer
  resourceAmounts = 54,66;108;132
  basePartMass =0.075
  displayCurrentTankCost = false
  hasGUI = true
  availableInFlight = false
  availableInEditor = true
  showInfo = true
 }
}
@PART[OscarEtank]:FINAL
{
 MODULE
 {
  name = FSfuelSwitch
  resourceNames = LiquidFuel,Oxidizer;LiquidFuel;Oxidizer
  resourceAmounts = 108,132;216;264
  basePartMass =0.15
  displayCurrentTankCost = false
  hasGUI = true
  availableInFlight = false
  availableInEditor = true
  showInfo = true
 }
}
```

As TAC-LS and USI-LS are mutually exclusive, wouldn't it be possible to add similar code under the existing framework of converter replacement?

And BTW, how do I attach the Feature Request label?

**Comment by BobPalmer** [comment]
It's not adding the module that's complicated, rather it's the extension of existing modules (and god help us, having to have their visibility be dynamic).  You may want to take a look and see just how extensive my FSFuelSwitch modules are.  Oh... and custom textures.  Also the issue of doing all of the conversions - i.e. I can't just plunk even ratios, I have to make sure they match the appropriate TAC-LS ratios.  Then price them out so cost is balanced.

My policy regarding mods I do not use myself is that I will take pull requests.  So if someone gets enterprising and sends one, I'll be happy to look at it.

**Comment by BobPalmer** [comment]
Closing until such time as someone sends a completed pull request
