### ISSUE TITLE
Kontainer tanks not working with symmetry

### ISSUE THREAD

**Issue by Rodg88** [UmbraSpaceIndustries/USITools#36]
(copied from my forum post)

I'm having a problems with switching the texture and resource type on the spherical and cylindrical kontainer tanks, and attaching them with symmetry. Basically attaching them with symmetry (or just having symmetrical ghost parts appear from mousing over a part while holding a tank) will change the tank resource to match the index of the colour texture...

For example, place a single 1.25m tank, change the resource and leave it gold. Then pick it up and place it radially with symmetry, and the resource will change back to LFO (gold and LFO are both the first options for the texture switches). Then try it again, leaving the tank set to LFO this time, but change the colour to copper, and then attach radially with symmetry, and the resource will change to H20 (copper and H20 are both the second options for the texture switches, so it seems the resource switch is changing to match the colour switch index).

Trying to switch stuff on a part already in a symmetrical set also causes weird problems, and attaching radially without symmetry doesn't.

**Comment by Jimbodiah** [comment]
Same here.

**Comment by BobPalmer** [comment]
Fixed in next release

**Comment by Jimbodiah** [comment]
:100:
