### ISSUE TITLE
Average pulse drive thrust is unaffected by the throttle position

### ISSUE THREAD

**Issue by tsbockman** [UmbraSpaceIndustries/USITools#37]
My testing indicates that the Orion drive always produces the same amount of thrust (averaged over a few cycles), even if I set the throttle as low as 1/3.

Based on the source code, it appears that the plug-in currently responds to reduced throttle by simply lowering the frequency of the roughly sinusoidal thrust curve (and the animation). This has no affect on the average thrust at all; the longer low-thrust periods are exactly cancelled out by the longer high-thrust periods. (It also makes no sense physically.)

This also means that the `maxPulseTime` and `minPulseTime` _cfg_ parameters are purely cosmetic, whereas I had expected the thrust to be scaled by `1.0 / minPulseTime`.

Possible fixes:
- Don't support throttling, except as on/off. This would be entirely reasonable, given how an NPE works.
- Make each pulse last `minPulseTime`, but after each pulse zero out the thrust completely for a throttle-dependant delay before the next one.
- Instead of messing with the timing, Use the throttle to select the NPU type - for example, 100% throttle for NPU-2500, vs 20% throttle for NPU-250.
- Or, Just directly scale the thrust - chalk it up to [variable yield](https://en.wikipedia.org/wiki/Variable_yield) NPUs. Efficiency (effective specific impulse) would be lower when throttling.

Personally, I'd like to see throttle-based selection of the NPU type, combined with a magazine UI that enables easy mix-and-match of sizes. I think it's the most realistic option, and shouldn't be too hard to implement.

**Comment by Jimbodiah** [comment]
The thrust is not limited, just the rate of firing. Each pelet gives the same thrust, you just select how long.short the interval between them is. The scaling is not quite linear though, but you can set it to slow/fast (though not much in between).

**Comment by tsbockman** [comment]
Each charge should give the same impulse (N*s), which means the same change in velocity (m/s) if the ship's mass is held constant.

Currently they do not. Instead, throttling down stretches out the length of each pulse in time, without reducing the average thrust or the duty cycle.

The result is that throttling down effectively makes each bomb _more powerful_, contrary to physics. You can increase your fuel efficiency by throttling down, and you'll still finish the burn just as fast as you would at max throttle. This is wrong; it's a bug, plain and simple.

**Comment by Jimbodiah** [comment]
:+1:  I didn't look that far into it, just that it was off. I haven't really used the mod, as applications are limited.

**Comment by tsbockman** [comment]
> I haven't really used the mod, as applications are limited.

I like to think of Orion as the ultimate embodiment of the "Problems? Try _MOAR_ BOOSTERS!" meme.

**Comment by Jimbodiah** [comment]
LOL... I think they ran out of boosters and started using the warheads :)

**Comment by BobPalmer** [comment]
Corrected in next release

**Comment by tsbockman** [comment]
@BobPalmer 

> Corrected in next release

[This appears to work correctly for the Orion Drive,](https://github.com/BobPalmer/UmbraSpaceIndustries/commit/f744e18c75eb4744a39da781e3927fc85352f6a4) assuming you mean to implement this option:

> Make each pulse last minPulseTime, but after each pulse zero out the thrust completely for a throttle-dependant delay before the next one.

But I think it will still produce a lot of excess thrust (causing effective Isp to rise) at low throttle for Medusa, because the `pulseCurve` doesn't end at `0` [unless `powerCurve` is `1`](https://github.com/BobPalmer/NuclearRockets/blob/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/Orion/Parts/Medusa.cfg#L55).

**Comment by tsbockman** [comment]
The best fix for the general case would probably be to always use a `pulseCurve` that ends at `0`, and just overlay two instances of it when firing the engine at full speed. You might need to add an extra point or three to the curve to keep the sum roughly sinusoidal, though.

**Comment by tsbockman** [comment]
(This is actually related to the reason that a variable pulse rate would be somewhat tricky to make work safely in real life: at maximum firing rate, each pulse goes off while the pusher plate is still recovering from the previous one.

They are timed to provide the smoothest ride possible, but that timing gets messed up as soon as you start slowing down the firing rate. To avoid exceeding the G-force limits due to constructive interference of the pulse curves, they planned to only use half-yield bombs when firing at anything less than full rate - including for the first and last pulse in a sequence.

That doesn't mean _you_ have to do it that way; your drive already has _far_ higher Isp than the proposed first generation models, so why not higher G limits?

But it is interesting to see how the difficulties in simulating the problem properly mirror the ones they expected to face if they actually built it...)
