### ISSUE TITLE
Unable to salvage parts in ksp 1.0.5

### ISSUE THREAD

**Issue by pda0** [UmbraSpaceIndustries/USITools#54]
Starting at 1.1 compatibility. There an error in ksp.log:

[ERR 00:31:55.547] AssemblyLoader: Exception loading 'USITools': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'USITools.USIAnimation' from assembly 'USITools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Also can't switch to 1.1 since at least half mods still not updated.

**Comment by BobPalmer** [comment]
Closing, as the currently supported version is 1.1
