### ISSUE TITLE
Karbonite Converter produced LF if tank is locked (red circle)

### ISSUE THREAD

**Issue by haslingerm** [UmbraSpaceIndustries/USITools#6]
As reported by FortisVenaliter [in the Karbonite DEV thread](http://forum.kerbalspaceprogram.com/threads/87335-24-2-Karbonite-Ongoing-Dev-and-Discussion/page200?p=1413206#post1413206) the converter continues consuming Karbonite while not creating any LF if the (LF) tank is locked. 
The problem is, that LF has a STACK_PRIO flow mode, but [its space availability is checked as ALL_VESSEL](https://github.com/BobPalmer/UmbraSpaceIndustries/blob/master/USI_Converter/USI_Converter/PartExtensions.cs#L298).
I'm pretty sure FortisVenaliter had another LF tank in another stage which was not locked. A quick test I performed showed, that if all tanks on the current stage are locked but there is an unlocked, non-empty one on another stage the converter sees available space and continues production while the LF is dumped because no space on this stage (since we are using part.TakeResource(-value) to add resources this is affected by the lock as well).

I'm currently too busy to fix it myself but wanted to report it anyway.

**Comment by BobPalmer** [comment]
This should be fixed with Regolith, closing
