### ISSUE TITLE
'Rovers' can only Scavenge short-range for their own needs

### ISSUE THREAD

**Issue by sirreality** [UmbraSpaceIndustries/USITools#60]
[ModuleLogigisticsConsumer](https://github.com/BobPalmer/UmbraSpaceIndustries/blob/master/USITools/USITools/Logistics/ModuleLogisticsConsumer.cs) only uses a ModuleResourceDistributor part to extend the scavenging range if it is on another vessel.  Thus, a piloted rover will starve unless <150m from Supplies warehouse, despite shuttling Supplies 2km away.  Suggested fix includes checking if the current vessel has a part with ModuleResourceDistributor, and if so, setting it's ScavangeRange to 2000, otherwise letting it keep the default configured ScavangeRange of 150.

Also, it's scavEnge, not scavAnge.

**Comment by BobPalmer** [comment]
Looks to be corrected in the next update.
