### ISSUE TITLE
KSP 1.2.2 Compatibility

### ISSUE THREAD

**Issue by nalbeza** [UmbraSpaceIndustries/USITools#79]
Hello,

It seems this mod is not compatible with KSP 1.2.2 64bit, which Steam forced me to update to.

When launching the game, i'm greeted by an incompatibility error message:
"Unsupported KSP version, please use 1.2.1"

Do you think a version bump would be enough to make it work ?

I'm going to test that in the meantime :-)

Thank you !

**Comment by Forgilageord** [comment]
Have you tried using it anyway? AVC will say that with any mod built for a previous version, whether or not it actually works.

**Comment by BobPalmer** [comment]
This works in 1.2.2, and an official patch is coming out shortly.
