### ISSUE TITLE
NullRef exception from ground tether

### ISSUE THREAD

**Issue by pellinor0** [UmbraSpaceIndustries/USITools#89]
NullReferenceException: Object reference not set to an instance of an object
  at USITools.ModuleStabilization.FixedUpdate () [0x00000] in <filename unknown>:0 

Repro: 
* build a craft with a MKS ranger ISM
* launch
* click "toggle ground tether"
* quicksave
* quickload

In a debug install with only USI I get this once after a quickload. In a modded install with a larger craft I get it five times (still only one active ground tether).

**Comment by BobPalmer** [comment]
Just performed this with no issues, closing as I cannot repro
